<?php

namespace Database\Seeders;

use App\Models\Auction;
use Illuminate\Database\Seeder;

class AuctionSeeder extends Seeder
{
    public function run(): void
    {
        $auctions = [
            [
                'title' => 'Rumah Tinggal SHM Dijual Lelang di Pangkalpinang',
                'auction_number' => '019/2026/ALA',
                'description' => 'Rumah tinggal 2 lantai dengan bangunan kokoh, lokasi strategis dekat pusat kota Pangkalpinang. Akses mudah ke jalan utama dan dekat dengan fasilitas umum. Cocok untuk tempat tinggal maupun investasi properti.',
                'asset_type' => 'rumah',
                'asset_description' => 'Rumah tinggal dengan 3 kamar tidur, 2 kamar mandi, ruang tamu luas, dapur, dan carport 2 mobil. Bangunan berdiri di atas lahan datar 180 m² dengan luas bangunan 120 m², SHM atas nama debitur.',
                'building_condition' => 'Bagus',
                'certificate_type' => 'SHM',
                'certificate_number' => 'SHM No. 10234/Pair Itam',
                'land_area' => 180,
                'building_area' => 63,
                'address' => 'Jl. Soekarno Hatta No. 12',
                'village' => 'Air Itam',
                'district' => 'Bukit Intan',
                'city' => 'Pangkalpinang',
                'province' => 'Kepulauan Bangka Belitung',
                'postal_code' => '33684',
                'debtor_name' => 'Budi Santoso',
                'auction_type' => 'eksekusi_hak_tanggungan',
                'auction_date' => now()->addDays(10)->toDateString(),
                'auction_time' => '11:00:00',
                'auction_location' => 'KPKNL Pangkalpinang',
                'auction_url' => 'https://portal.lelang.go.id',
                'organizer_name' => 'KPKNL Pangkalpinang',
                'limit_price' => 525000000,
                'estimated_price' => 650000000,
                'deposit_amount' => 52500000,
                'contact_name' => 'Hendra Gunawan',
                'contact_phone' => '0812-7000-8890',
                'contact_email' => 'lelang@bprsbabel.co.id',
                'status' => 'registration_open',
                'is_featured' => true,
                'view_count' => 34,
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'Tanah Kosong SHM - Sungailiat, Bangka',
                'auction_number' => '017/2026/ALA',
                'description' => 'Lahan tanah kosong seluas 200 m² dengan SHM. Lokasi strategis di Jl. Raya Sungailiat, sangat potensial untuk pembangunan.',
                'asset_type' => 'tanah',
                'asset_description' => 'Tanah kosong datar dengan ukuran 10m x 20m (200 m²), lokasi menghadap jalan raya, dekat dengan perumahan dan pertokoan.',
                'certificate_type' => 'SHM',
                'certificate_number' => 'SHM/2025/busung',
                'land_area' => 200,
                'address' => 'Jl. Raya Sungai Notok',
                'village' => 'Sungai Busung',
                'district' => 'Sungai Notok',
                'city' => 'Sungai Liat',
                'province' => 'Kepulauan Bangka Belitung',
                'debtor_name' => 'Maya Silvia',
                'auction_type' => 'eksekusi_hak_tanggungan',
                'auction_date' => now()->addDays(16)->toDateString(),
                'auction_time' => '10:00:00',
                'auction_location' => 'KPKNL Pangkalpinang',
                'auction_url' => 'https://portal.lelang.go.id',
                'organizer_name' => 'KPKNL Pangkalpinang',
                'limit_price' => 185000000,
                'estimated_price' => 210000000,
                'deposit_amount' => 18500000,
                'contact_name' => 'Renaldi Putra',
                'contact_phone' => '0821-5000-1133',
                'contact_email' => 'info@bprs-babel.co.id',
                'status' => 'published',
                'is_featured' => false,
                'view_count' => 12,
                'published_at' => now(),
            ],
            [
                'title' => 'Ruko 2 Lantai - Tanjungpandan',
                'auction_number' => '014/2025/ALB',
                'description' => 'Ruko 2 lantai di lokasi bisnis Tanjungpandan, laik jual dengan harga menarik. Cocok untuk toko, kantor, atau gudang.',
                'asset_type' => 'ruko',
                'asset_description' => 'Ruko 2 lantai dengan ukuran 5m x 15m, bangunan kondisi baik, di jalan utama perniagaan.',
                'building_condition' => 'Bagus',
                'certificate_type' => 'SHGB',
                'certificate_number' => 'SHGB/2020/Perek',
                'land_area' => 72,
                'building_area' => 117,
                'address' => 'Jl. Jendral Sudirman No. 12',
                'village' => 'Kampung Bugis',
                'district' => 'Tanjungpandan',
                'city' => 'Tanjungpandan',
                'province' => 'Kepulauan Bangka Belitung',
                'postal_code' => '33511',
                'debtor_name' => 'Rara Astuti',
                'auction_type' => 'non_eksekusi_wajib',
                'auction_date' => now()->addDays(30)->toDateString(),
                'auction_time' => '14:00:00',
                'auction_location' => 'KPKNL Tanjungpandan',
                'auction_url' => 'https://portal.lelang.go.id',
                'organizer_name' => 'KPKNL Tanjungpandan',
                'limit_price' => 310000000,
                'estimated_price' => 350000000,
                'deposit_amount' => 31000000,
                'contact_name' => 'Dina',
                'contact_phone' => '0818-2200-9080',
                'contact_email' => 'dina@bprs-babel.co.id',
                'status' => 'sold',
                'is_featured' => true,
                'view_count' => 89,
                'published_at' => now()->subDays(20),
            ],
        ];

        foreach ($auctions as $item) {
            Auction::create($item);
        }
    }
}
